# 1. torch.gather  在指定的轴上，根据给定的index进行索引
torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor

In [7]:
import torch

In [10]:
# dim=0 表示沿着行进行操作，列的行
# dim=1 表示沿着列进行操作，行的列
t = torch.tensor([[1, 2], 
                  [3, 4]])
torch.gather(t, 0, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 2]])

In [11]:
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [14]:
# 假设 input 是一个三维张量
input = torch.tensor([
    [[1, 2, 3], 
     [4, 5, 6], 
     [7, 8, 9]],
    [[10, 11, 12], 
     [13, 14, 15], 
     [16, 17, 18]],
    [[19, 20, 21], 
     [22, 23, 24], 
     [25, 26, 27]]
])

# ndex 是一个三维张量，其维度必须与 input 相同
# index 的每个元素表示在 input 相应位置处要选择的索引
index = torch.tensor([
    [[0, 2, 1], [1, 0, 2], [2, 1, 0]],
    [[2, 1, 0], [0, 2, 1], [1, 0, 2]],
    [[1, 0, 2], [2, 1, 0], [0, 2, 1]]
])

# dim=0 表示沿着第一个维度（批处理维度）进行操作
# dim=1 表示沿着第二个维度（行）进行操作
# dim=2 表示沿着第三个维度（列）进行操作

In [16]:
# dim=0 表示沿着第一个维度（批处理维度）进行操作，每个批次的index对应位置
torch.gather(input, dim=0, index=index)
# [0,2,1] --> 0：第0批次的第1行的第1个元素。2：第2批次的第1行的第2个元素。1：第1批次的第1行的第3个元素。
# [1,0,2] --> 1：第1批次的第2行的第1个元素。0：第0批次的第2行的第2个元素。2：第2批次的第2行的第3个元素。

tensor([[[ 1, 20, 12],
         [13,  5, 24],
         [25, 17,  9]],

        [[19, 11,  3],
         [ 4, 23, 15],
         [16,  8, 27]],

        [[10,  2, 21],
         [22, 14,  6],
         [ 7, 26, 18]]])

In [15]:
# dim=1 表示沿着第二个维度（行）进行操作，每列的行
torch.gather(input, dim=1, index=index)

tensor([[[ 1,  8,  6],
         [ 4,  2,  9],
         [ 7,  5,  3]],

        [[16, 14, 12],
         [10, 17, 15],
         [13, 11, 18]],

        [[22, 20, 27],
         [25, 23, 21],
         [19, 26, 24]]])

In [17]:
# dim=2 表示沿着第三个维度（列）进行操作，每行的列
torch.gather(input, dim=2, index=index)

tensor([[[ 1,  3,  2],
         [ 5,  4,  6],
         [ 9,  8,  7]],

        [[12, 11, 10],
         [13, 15, 14],
         [17, 16, 18]],

        [[20, 19, 21],
         [24, 23, 22],
         [25, 27, 26]]])